async function startProgram() {
	await speak('Βρες το απαλό', true);
	setMainLed({ r: 255, g: 12, b: 209 });
	await delay(10);
	await spin(2000, 2);
	await Sound.Effects.Fairy.play(true);
	await speak('Βρες το τραχύ', true);
	setMainLed({ r: 55, g: 210, b: 255 });
	await delay(10);
	await spin(2000, 6);
	await Sound.Effects.Fairy.play(true);
	await speak('Βρες το λείο', true);
	setMainLed({ r: 244, g: 216, b: 18 });
	await delay(10);
	await spin(2000, 6);
	await Sound.Effects.Fairy.play(true);
	await speak('Βρες το απαλό ', true);
	setMainLed({ r: 244, g: 24, b: 194 });
	await delay(10);
	await spin(2000, 6);
	await Sound.Effects.Fairy.play(true);
	await speak('Βρες το τραχύ ', true);
	setMainLed({ r: 81, g: 231, b: 244 });
	await delay(10);
	await spin(2000, 6);
	await Sound.Effects.Fairy.play(true);
	await speak('Βρες το λείο', true);
	setMainLed({ r: 244, g: 216, b: 18 });
	await delay(10);
	await spin(2000, 6);
	await Sound.Effects.Fairy.play(true);
	await speak('Βρες το απαλό ', true);
	setMainLed({ r: 244, g: 24, b: 194 });
	await delay(10);
	await spin(2000, 6);
	await Sound.Effects.Fairy.play(true);
	await speak('Βρες το λείο', true);
	setMainLed({ r: 244, g: 200, b: 34 });
	await delay(10);
	await spin(2000, 6);
	await Sound.Effects.Fairy.play(true);
	await speak('Βρες το απαλό', true);
	setMainLed({ r: 244, g: 25, b: 199 });
	await delay(10);
	await spin(2000, 6);
	await Sound.Effects.Fairy.play(true);
	await speak('Βρες το λείο ', true);
	setMainLed({ r: 244, g: 216, b: 18 });
	await delay(2);
	await spin(2000, 6);
	await Sound.Effects.Fairy.play(true);
	await speak('Μπράβο τα κατάφερες!!!', true);
	await Sound.Effects.JokeDrum.play(false);
	await spin(3000, 3);
}
